import type { Product, Category, User, Order } from './types';

export const categories: Category[] = [
  { id: 'cat1', name: 'Fresh Food', slug: 'fresh-food', imageUrl: 'https://picsum.photos/seed/31/400/300', imageHint: 'fresh produce' },
  { id: 'cat7', name: 'Packaged Food & Groceries', slug: 'packaged-food-groceries', imageUrl: 'https://picsum.photos/seed/32/400/300', imageHint: 'grocery aisle' },
  { id: 'cat8', name: 'Beverages', slug: 'beverages', imageUrl: 'https://picsum.photos/seed/33/400/300', imageHint: 'drink bottles' },
  { id: 'cat9', name: 'Personal Care & Beauty', slug: 'personal-care-beauty', imageUrl: 'https://picsum.photos/seed/34/400/300', imageHint: 'cosmetic products' },
  { id: 'cat5', name: 'Home & Kitchen', slug: 'home-kitchen', imageUrl: 'https://picsum.photos/seed/35/400/300', imageHint: 'kitchen supplies' },
  { id: 'cat2', name: 'Electronics & Gadgets', slug: 'electronics-gadgets', imageUrl: 'https://picsum.photos/seed/36/400/300', imageHint: 'electronic devices' },
  { id: 'cat3', name: 'Clothing & Fashion', slug: 'clothing-fashion', imageUrl: 'https://picsum.photos/seed/37/400/300', imageHint: 'fashion apparel' },
  { id: 'cat10', name: 'Baby Products', slug: 'baby-products', imageUrl: 'https://picsum.photos/seed/38/400/300', imageHint: 'baby toys' },
  { id: 'cat11', name: 'Pet Supplies', slug: 'pet-supplies', imageUrl: 'https://picsum.photos/seed/39/400/300', imageHint: 'dog treats' },
  { id: 'cat4', name: 'Office & School Supplies', slug: 'office-school-supplies', imageUrl: 'https://picsum.photos/seed/40/400/300', imageHint: 'school stationery' },
];

export const products: Product[] = [
  {
    id: 'prod1',
    slug: 'fresh-mangoes',
    name: 'Fresh Mangoes (Each)',
    description: 'Sweet, juicy, and packed with tropical flavor. Perfect for smoothies, salads, or a healthy snack.',
    price: 1.50,
    category: 'fresh-food',
    imageUrl: 'https://picsum.photos/seed/201/600/400',
    imageHint: 'ripe mangoes',
    stock: 150,
    requiresRefrigeration: true,
    safetyWarnings: 'Wash before eating.'
  },
  {
    id: 'prod2',
    slug: 'organic-spinach',
    name: 'Organic Spinach (250g)',
    description: 'Freshly harvested organic spinach, rich in iron and vitamins. Ideal for salads, sautés, and green smoothies.',
    price: 3.00,
    category: 'fresh-food',
    imageUrl: 'https://picsum.photos/seed/202/600/400',
    imageHint: 'bunch spinach',
    stock: 80,
    requiresRefrigeration: true,
    careGuidelines: 'Keep refrigerated in a crisper drawer. Use within 3-5 days for optimal freshness.',
  },
  {
    id: 'prod3',
    slug: 'hass-avocados',
    name: 'Hass Avocados (Each)',
    description: 'Creamy and delicious Hass avocados. Perfect for toast, guacamole, or adding to salads.',
    price: 2.00,
    category: 'fresh-food',
    imageUrl: 'https://picsum.photos/seed/203/600/400',
    imageHint: 'green avocados',
    stock: 200,
  },
  {
    id: 'prod4',
    slug: 'aero-pods-pro',
    name: 'AeroPods Pro',
    description: 'Immersive sound, active noise cancellation, and a customizable fit. Your everyday audio companion.',
    price: 249.99,
    category: 'electronics-gadgets',
    imageUrl: 'https://picsum.photos/seed/204/600/400',
    imageHint: 'pro earbuds',
    stock: 50,
    usageInstructions: 'Open the case near your phone and tap Connect. Place in your ears to play audio.',
    warrantyInformation: '1-Year Limited Warranty.'
  },
  {
    id: 'prod5',
    slug: 'nexus-10-smartphone',
    name: 'Nexus 10 Smartphone',
    description: 'A powerful smartphone with a stunning 6.7-inch display, pro-grade camera system, and all-day battery life.',
    price: 999.00,
    category: 'electronics-gadgets',
    imageUrl: 'https://picsum.photos/seed/205/600/400',
    imageHint: 'nexus smartphone',
    stock: 35,
    warrantyInformation: '1-Year Manufacturer Warranty.'
  },
  {
    id: 'prod6',
    slug: 'ultra-slim-laptop',
    name: 'UltraSlim Laptop 14"',
    description: 'Experience incredible performance in a sleek, lightweight design. Perfect for work, study, and entertainment on the go.',
    price: 1299.00,
    category: 'electronics-gadgets',
    imageUrl: 'https://picsum.photos/seed/206/600/400',
    imageHint: 'ultraslim laptop',
    stock: 20,
  },
  {
    id: 'prod7',
    slug: 'classic-cotton-t-shirt',
    name: 'Classic Cotton T-Shirt',
    description: 'A comfortable and versatile t-shirt made from 100% premium cotton. Available in various colors.',
    price: 19.99,
    category: 'clothing-fashion',
    imageUrl: 'https://picsum.photos/seed/207/600/400',
    imageHint: 'white t-shirt',
    stock: 300,
    careGuidelines: 'Machine wash cold, tumble dry low. Do not bleach.'
  },
  {
    id: 'prod8',
    slug: 'denim-jeans',
    name: 'Slim Fit Denim Jeans',
    description: 'Modern slim fit jeans crafted from durable stretch denim for all-day comfort and style.',
    price: 59.99,
    category: 'clothing-fashion',
    imageUrl: 'https://picsum.photos/seed/208/600/400',
    imageHint: 'denim pants',
    stock: 120,
  },
  {
    id: 'prod9',
    slug: 'trail-runner-shoes',
    name: 'TrailRunner X1 Shoes',
    description: 'Lightweight and durable running shoes designed for maximum comfort and support on any terrain.',
    price: 89.99,
    category: 'clothing-fashion',
    imageUrl: 'https://picsum.photos/seed/209/600/400',
    imageHint: 'trail shoes',
    stock: 90,
  },
  {
    id: 'prod10',
    slug: 'ergonomic-office-chair',
    name: 'Ergonomic Office Chair',
    description: 'Stay comfortable and productive with this ergonomic office chair featuring lumbar support and adjustable armrests.',
    price: 179.99,
    category: 'office-school-supplies',
    imageUrl: 'https://picsum.photos/seed/210/600/400',
    imageHint: 'ergonomic chair',
    stock: 40,
    assemblyInstructions: 'Simple 5-step assembly with included tools. Estimated time: 15 minutes.'
  },
  {
    id: 'prod11',
    slug: 'a4-printer-paper',
    name: 'A4 Printer Paper (500 Sheets)',
    description: 'High-quality 80gsm printer paper for crisp, clear printing. Perfect for office and home use.',
    price: 7.99,
    category: 'office-school-supplies',
    imageUrl: 'https://picsum.photos/seed/211/600/400',
    imageHint: 'paper ream',
    stock: 500,
  },
  {
    id: 'prod12',
    slug: 'lemon-dish-soap',
    name: 'Lemon Fresh Dish Soap (750ml)',
    description: 'Tough on grease, gentle on hands. Leaves your dishes sparkling clean with a fresh lemon scent.',
    price: 4.50,
    category: 'home-kitchen',
    imageUrl: 'https://picsum.photos/seed/212/600/400',
    imageHint: 'lemon soap',
    stock: 250,
  },
  {
    id: 'prod13',
    slug: 'multi-surface-cleaner',
    name: 'Multi-Surface Cleaner',
    description: 'A powerful all-purpose cleaner that cuts through dirt and grime on a variety of surfaces.',
    price: 5.99,
    category: 'home-kitchen',
    imageUrl: 'https://picsum.photos/seed/213/600/400',
    imageHint: 'cleaning spray',
    stock: 180,
    safetyWarnings: 'Keep out of reach of children. Avoid contact with eyes.'
  },
  {
    id: 'prod14',
    slug: 'coca-cola-can',
    name: 'Coca-Cola (330ml Can)',
    description: 'The classic, refreshing taste of Coca-Cola. Best served chilled.',
    price: 0.80,
    category: 'beverages',
    imageUrl: 'https://picsum.photos/seed/214/600/400',
    imageHint: 'soda can',
    stock: 400,
  },
  {
    id: 'prod15',
    slug: 'mineral-water',
    name: 'Mineral Water (1.5L)',
    description: 'Pure, natural mineral water sourced from the highlands. Essential for hydration.',
    price: 1.20,
    category: 'beverages',
    imageUrl: 'https://picsum.photos/seed/215/600/400',
    imageHint: 'bottled water',
    stock: 300,
  },
  {
    id: 'prod16',
    slug: 'gentle-bar-soap',
    name: 'Gentle Moisturizing Bar Soap',
    description: 'A mild and moisturizing bar soap that cleanses without drying out your skin.',
    price: 2.50,
    category: 'personal-care-beauty',
    imageUrl: 'https://picsum.photos/seed/216/600/400',
    imageHint: 'bar soap',
    stock: 200,
  },
  {
    id: 'prod17',
    slug: 'daily-moisture-shampoo',
    name: 'Daily Moisture Shampoo (400ml)',
    description: 'Hydrating shampoo for all hair types. Leaves hair soft, shiny, and manageable.',
    price: 6.99,
    category: 'personal-care-beauty',
    imageUrl: 'https://picsum.photos/seed/217/600/400',
    imageHint: 'shampoo bottle',
    stock: 150,
  },
  {
    id: 'prod18',
    slug: 'non-stick-cooking-pot',
    name: 'Non-Stick Cooking Pot (5L)',
    description: 'A versatile non-stick pot with a glass lid, perfect for stews, soups, and more.',
    price: 35.00,
    category: 'home-kitchen',
    imageUrl: 'https://picsum.photos/seed/218/600/400',
    imageHint: 'cooking pot',
    stock: 60,
  },
  {
    id: 'prod19',
    slug: 'baby-diapers-pack',
    name: 'Super-Absorbent Diapers (Pack of 50)',
    description: 'Leak-proof diapers designed for maximum comfort and up to 12 hours of protection.',
    price: 15.99,
    category: 'baby-products',
    imageUrl: 'https://picsum.photos/seed/219/600/400',
    imageHint: 'baby diapers',
    stock: 100,
  },
  {
    id: 'prod20',
    slug: 'dry-dog-food',
    name: 'Complete Nutrition Dry Dog Food (5kg)',
    description: 'A balanced and complete dry food formula for adult dogs, with all essential vitamins and minerals.',
    price: 25.50,
    category: 'pet-supplies',
    imageUrl: 'https://picsum.photos/seed/220/600/400',
    imageHint: 'dog food',
    stock: 70,
  }
];

export const users: User[] = [
  {
    id: 'user1',
    name: 'Jane Doe',
    email: 'jane.doe@example.com',
    addresses: ['123 Savanna Close, Nairobi, Kenya'],
    wishlist: ['prod4', 'prod9']
  }
];

export const orders: Order[] = [
    {
        id: 'ord1',
        date: '2024-07-28',
        items: [
            { productId: 'prod1', quantity: 4, price: 1.50 },
            { productId: 'prod2', quantity: 2, price: 3.00 }
        ],
        total: 12.00,
        status: 'Delivered'
    },
    {
        id: 'ord2',
        date: '2024-08-10',
        items: [
            { productId: 'prod7', quantity: 2, price: 19.99 },
            { productId: 'prod8', quantity: 1, price: 59.99 }
        ],
        total: 99.97,
        status: 'Shipped'
    },
    {
        id: 'ord3',
        date: '2024-08-15',
        items: [
            { productId: 'prod5', quantity: 1, price: 999.00 }
        ],
        total: 999.00,
        status: 'Processing'
    }
];
